
import type { Metadata } from "next";

import "@/styles/main.scss";
import Providers from "@/content/Providers";




export const metadata: Metadata = {
  title: "Korb Delivery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <link
        href='https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap'
        rel='stylesheet'
      />
      <body className= "antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
