import type { Metadata } from "next";
//import localFont from "next/font/local";
import "@/styles/main.scss";
import Providers from "@/content/Providers";



// const montserrat = localFont({
//   src: '/fonts/Montserrat-ExtraBold.woff', 
//   variable: '--font-montserrat',
//   weight: '800 900',
// });
export const metadata: Metadata = {
  title: "Korb Delivery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <link
        href='https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap'
        rel='stylesheet'
      />
      <body className= "antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
